games/core/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from .views import (
    CSVUploadView,
    GetGamesView,
    GetScoresView,
    HandleUploadView,
    HomeTemplateView,
)

app_name = "core"

router = SimpleRouter()
router.register("games", GetGamesView, basename="games"),


urlpatterns = router.urls

urlpatterns += [
    path("", HomeTemplateView.as_view(), name="home"),
    path("csv-upload/", CSVUploadView.as_view(), name="csv_upload"),
    path("import-data/", HandleUploadView.as_view(), name="import_data"),
    path("get-scores/", GetScoresView.as_view(), name="get_scores"),
]

games/games/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls", namespace="user")),
    path("", include("djvue.urls")),
]

games/user/urls.py
from django.urls import path
from .views import RegisterView

app_name = 'user'

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
]

games/core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Team(models.Model):
    """add team """
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    """add game class"""
    team1 = models.ForeignKey('Team', on_delete= models.CASCADE, related_name="games1")
    team1_score = models.IntegerField()
    team2 = models.ForeignKey('Team', on_delete= models.CASCADE, related_name="games2")
    team2_score = models.IntegerField()

    class Meta:
        verbose_name = _("Game")
        verbose_name_plural = _("Games")

    def __str__(self):
        return self.team1.name + self.team2.name

games/user/models.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

games/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

games/core/views.py
from django.views.generic import TemplateView
from djvue.views import FileUploadView
from rest_framework import status, viewsets
from rest_framework.mixins import DestroyModelMixin, ListModelMixin, UpdateModelMixin, CreateModelMixin
from rest_framework.permissions import AllowAny, IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView

from .helper_functions import get_score
from .models import Game
from .serializers import CSVUploadSerializer, GameSerializer, HandleUploadSerializer


class HomeTemplateView(TemplateView):
    template_name = "home.html"


class CSVUploadView(FileUploadView):
    serializer_class = CSVUploadSerializer


class HandleUploadView(APIView):
    permission_classes = (AllowAny,)

    def post(self, request, *args, **kwargs):
        serializer = HandleUploadSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class GetScoresView(APIView):
    permission_classes = (AllowAny,)

    def get(self, request, **kwargs):
        return Response(get_score())


class GetGamesView(
    CreateModelMixin,
    ListModelMixin,
    UpdateModelMixin,
    DestroyModelMixin,
    viewsets.GenericViewSet,
):
    queryset = Game.objects.all()
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = GameSerializer

games/user/views.py
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic import CreateView
from .forms import RegisterForm


class RegisterView(CreateView):
    template_name = "registration/register.html"
    success_url = reverse_lazy('login')
    form_class = RegisterForm

games/templates/base.html
{% load vue_tags %}
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="utf-8"/>
    <title> games </title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

</head>

<body class="{% block body_class %}{% endblock %}">
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#bootstrap"></use>
        </svg>
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
    </ul>

    <div class="col-md-3 text-end">
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">
                <button type="button" class="btn btn-outline-primary me-2">Logout</button>
            </a>
        {% else %}
            <a href="{% url 'login' %}">
                <button type="button" class="btn btn-outline-primary me-2">Login</button>
            </a>
        {% endif %}
        <a href="{% url 'user:register' %}">
            <button type="button" class="btn btn-primary">Sign-up</button>
        </a>
    </div>
</header>

<main class="container">
    {% block content %}

    {% endblock %}
</main>


</body>
{% vue_starter %}
{% block extra_js %}
{% endblock %}
</html>

games/templates/get_scores.html
<div style="width: 50%; padding-left: 100px">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Rank</th>
            <th scope="col">Team</th>
            <th scope="col">Score</th>
        </tr>
        </thead>
        <tbody>
        {% for score in scores %}
        <tr>
            <th scope="row">#{{ forloop.counter }}</th>
            <td>score</td>
            <td>nn</td>
        <td>
                <button type="button" class="btn btn-outline-primary">update</button>
                <button type="button" class="btn btn-outline-danger">delete</button>
            </td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>

games/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div id="app" hidden>
        <div class="text">
            welcome
        </div>
        <br>
        <div class="form-control" id="fileUpload">
            <validation-observer ref="form" v-slot="{ handleSubmit }" mode="lazy">
                <form @submit.prevent="handleSubmit(submit)" novalidate="true" method=POST enctype=multipart/form-data>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name" class="control-label">Upload csv file </label>
                        <div class="col-md-5">
                            <validation-provider name="csv_file"
                                                 v-slot="{ errors, valid, invalid, validated, touched }" tag="div"
                                                 class="form-group"
                            >
                                <input type="file" name="csv_file" id="csv_file" class="form-control"
                                       accept=".csv, text/csv"
                                       @change="uploadFile($event, '{% url 'core:csv_upload' %}')">
                                <span v-for="error in errors" :key="error" class="invalid-feedback"
                                      style="display: inline">{( error )}</span>
                            </validation-provider>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                            <br>
                            <button class="btn btn-primary">Upload</button>
                        </div>
                    </div>

                </form>
            </validation-observer>

        </div>
        <br>

        <div id="getScores">
            <br>
            <div style="width: 50%; padding-left: 100px">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">num</th>
                        <th scope="col">team one</th>
                        <th scope="col">team one score</th>
                        <th scope="col">team two</th>
                        <th scope="col">team two score</th>
                        <th scope="col">action</th>
                    </tr>
                    </thead>
                    <tbody name="games">
                    <tr v-for="(game,index) in games" :key="game.pk">
                        <td>{(index+1)}</td>
                        <td><input type="text" v-model="game.team1.name"></td>
                        <td><input type="text" v-model="game.team1_score"></td>
                        <td><input type="text" v-model="game.team2.name"></td>
                        <td><input type="text" v-model="game.team2_score"></td>
                        <td>
                            {#                                <button type="button" class="btn btn-outline-primary" @click="update_game(game.pk")>update</button>#}
                            <button type="button" class="btn btn-outline-danger" @click="delete_game(game.pk)">delete
                            </button>
                            <button type="button" class="btn btn-outline-danger" @click="update_game(game.pk)">update
                            </button>
                        </td>
                    </tr>
                    {% if request.user.is_authenticated %}
                    <tr>
                        <td>Add Game:</td>
                        <td><input type="text" v-model="add_form.team1.name"></td>
                        <td><input type="text" v-model="add_form.team1_score"></td>
                        <td><input type="text" v-model="add_form.team2.name"></td>
                        <td><input type="text" v-model="add_form.team2_score"></td>
                        <td>
                            <button type="button" class="btn btn-outline-success" @click="add_game">Add</button>
                        </td>
                    </tr>
                    {% endif %}

                    </tbody>
                </table>
                <button v-if="previousGamesURL" @click="fetch_games(previousGamesURL)" class="btn btn-primary">
                    Previous
                </button>
                <button v-if="nextGamesURL" @click="fetch_games(nextGamesURL)" class="btn btn-primary">Next</button>


                <button type="submit" class="btn-default btn btn-success" @click="fetch_scores">show score</button>

            </div>

            <br>
            <br>
            <div style="width: 50%; padding-left: 100px">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#Rank</th>
                        <th scope="col">Team name</th>
                        <th scope="col">score</th>
                    </tr>
                    </thead>
                    <tbody name="scores">
                    <tr v-for="(score, index) in scores" :key="index">
                        <th>#{(index + 1)}</th>
                        <td>{(score.name)}</td>
                        <td>{(score.score)}</td>
                    </tr>
                    </tbody>
                </table>
                <br>


            </div>
        </div>

    </div>
{% endblock %}

{% block extra_js %}
    <script>

    </script>
    <script>
        {% include 'app.js' %}
    </script>
{% endblock %}